### ISSUE TITLE
Error: Logging level "0" does not exist!

### ISSUE THREAD

**Issue by radiocity** [hiddentao/gulp-server-livereload#42]
Just update node_modules. All task work perfect but livereload. Dunno why :(

**Comment by radiocity** [comment]
Changing `"gulp-server-livereload": "^1.5.4",` to `"gulp-server-livereload": "1.5.4"` solve the problem.

**Comment by hiddentao** [comment]
Could you try the latest version please (1.9.0).

**Comment by radiocity** [comment]
```
[16:20:24] Error: Logging level "0" does not exist!
    at formatError (C:\Users\radiocity\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\radiocity\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\OpenServer\domains\localhost\gulp\node_modules\orchestrator\index.js:264:8)
    at C:\OpenServer\domains\localhost\gulp\node_modules\orchestrator\index.js:275:23
    at finish (C:\OpenServer\domains\localhost\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\OpenServer\domains\localhost\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at apply (C:\OpenServer\domains\localhost\gulp\node_modules\thunks\thunks.js:362:38)
    at tryRun (C:\OpenServer\domains\localhost\gulp\node_modules\thunks\thunks.js:232:19)
[16:20:29] Finished 'build' after 5.19 s
```

It seems to be orchestrator module problem =_=
Changing gulp version not help. Problem still exists.

**Comment by hiddentao** [comment]
Is anyone else getting this?

**Comment by radiocity** [comment]
Error appears when `log` option set to `false`. Only string value `"info"` or `"debug"` should be defined.  
_PS Current issue thread was closed accidentally_
